# Generated by Django 5.0.2 on 2024-03-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('post', models.CharField(max_length=150, verbose_name='Должность')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('fired', models.BooleanField(default=False, verbose_name='Уволен')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.sector', verbose_name='Сектор')),
            ],
        ),
    ]
