# Generated by Django 5.0.3 on 2024-03-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_photo'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empskill',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
